server:
  ssl:
    key-store: classpath:https_keystore.p12
    key-store-password: chujian
    keyStoreType: PKCS12
    keyAlias: 1
  port: 8443
  http-port: 8080
  servlet:
    application-display-name: firstmeet-mservice-paycenter-chujian
    contextPath: /
  tomcat:
    basedir: "./"
    accesslog:
      enabled: true
      directory: ${FIRSTMEET_MSERVICE_DATA_BASEDIR:.}/logs/${HOSTNAME:1}/access-log
    customized.enable: true
    customized.accept-count: 100
    customized.max-threads: 200
    customized.min-spare-threads: 25
    customized.max-connections: 10000
    customized.connection-timeout: 2000
    manager.enable: false
    manager.context-path: '/data/webapps/manager'

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.220:3306/pay_center_chujian?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: kaifa
    password: chujian8
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

paycenter.chujian.host.url: 'https://upsdev.16801.com/chujianpay'

alipay:
  payment:
    url: 'https://openapi.alipay.com/gateway.do'
    notify.url: '${paycenter.chujian.host.url}/chujianpay/zfb/callback'
    return.url: 'TestSDK://TestSDK.13cd.com'
    appId: 2018012302042556
    private.key: 'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDRXUsN5/KDKpenY5DujAfyejnMviDE1vsv5tlr+NRNtw8o+0InKwDlxNz6xes3Nqutr1RgJ3a356qqBLkgjryThQ+TElx3/FSn8/EK4aT5buo7LUk9qWp+mWo3XIvK7M9UTHrfNKsEcidxZif6XZJFV1Dh1lBMkPTTYYx1pLxtxExhnSKl1BPdhMF/Rj34K0VjDcbU3ko7EP5RuzHmO8zoie90Q7vRf2yPIurQ6owAidbSZnfkcL8B69jWWJRENcQaV1eJINZEs2CUMkYfYnca184cxPvuWi12pnCbRjLtPBFqQrbwgt0xtLHWKaTRc1l3H0qCXANr84AiGXvndq1DAgMBAAECggEAcHm2QJpDZsQTBRIwYndILbQMKTpbUGROPcW/OIpNRBL8Sf/x4ijwKoBAV1jMrLTqNjzjD2UkGliTDxPKgPstw/LQEyriEnO05yXecQIYJwi3PWNu3XmOhMTWkzdcwn/GQntz50XcOl85YWqIP7DVS/tEsI76RKf7XzQgyXLe5/h7ZAwNkuPLva+AMqdjL/3yMyLOvIp60GfeUopWVhFq7JtAmiZHj474+7cSNdCm+rZ0dPxGXO+stdudCEwMgEW9A/Mu01ZnFF5rXzSJQKZM/8rKGZbQSaRFUzh0i3AmtUFvNB4ctB8c8Qyrd+vx+QWG0NuTeuR/h0LoGuku2r1YAQKBgQD9wu0vTnBR6604qy7GHWtj/rxYWPyGEZeX3/U+Me1ldSbXp72WurUVwCyUvFg8SzbtzEFsGMWsPDpMhm4BPozKGCenpLjX8fE10+NGZevyyEBcrYgoIfFfjrwvb/yxkJ8lhe6fcrQd20KS4LFAKbEIC6utcDNCbvaDTFslBszNgQKBgQDTNhqtmtr0e4Dg8DCrvtIDWr3157e3DZeKbusOoijR6ePIPkByS2KtwD7FcAzHkb5LpyZq81p/cvm23PegmiXxRV6b5JnTjJii8d5wecWG5Vo8aT1WU1PQHrncKPwCVyTjIFHgGUO3e9YjWKbqDtZjLENcOV1v37YzeJsxVJAkwwKBgECgy2136a1De6tqFZCJX5dpAijyCOZQRq58cGY1qwNi8dCMvQFNbd8rQW9kBIjekw+/LI5ORNHXyPVCa3PPrWWu/zJ4BkehK9CMtV5xiMUdcR7pZzrpYiL3JEBkohPLBG03Dg331Z2hAPSNWzc/JwIojsGuSK/LuOa5pKDqeXCBAoGBAJVjhUcZapjV6fgvqx0u4LhCrG2LsaOl13OwtE0rYRfoCJaPgWHV9DvU6BEaCc/2Q9Saq0+mRHI0zm8Kp5NOtFuMpzg4Xp0EqslFrgF7/7xD6Kkl/p5aXcOsl+Uij+zP2mVTbNXGyOC0lGd3wsd2KykGG7bVVENWxjZtrcccer+lAoGAEv8ZEG7aaMafktLA8X4vG0YlIbKrc07IAfEXD1PcsWdsTTsb34+X5J+TF4eHraylMwlVQdl8WykL1t2D0RgDNTjNL09forCh28Z/2lkmLHk1Oqcwwsn45JqbAD7a9i5VGOI+x447l5LJDg6InIuhyCwsWdsqzPtO4Bh9zfM+2qE='
    format: json
    charset: UTF-8
    public.key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnSOQxWARrqxmH3iBTY7R+2RRjF4ZqsyUAlZpgAulVTnRZC5IGoipULeHAqiTkZDMzKkyTZ2Z+IZNtswxgyfd7PsRuyeO8upcOx0+ad9OG4gR/wXHgx998QYtXNo30YODP41eyNe6Nycdd41r4SOnLuJNZCIKsxXw7MWFX8fMoh/nQb8IFOazgYvrpP2wXBjZebmAw2K8R7kDfjuB5ammzv+c9IaRDuudkgvzc3ocvJgzUWo2pETnOXCpFZtZ97NPUk6L5ILbPqS4BGeFk7n/c6tm7sZnbMZlUJKaqSBHty+06nUEOoWJ3zc4WN1HxQzixD37U1QttXgE/yNJcl+/9wIDAQAB'
    signType: RSA2

weixinpay:
        inter.order.url: 'https://api.mch.weixin.qq.com/pay/unifiedorder'
        inter.verify.url: 'https://api.mch.weixin.qq.com/pay/orderquery'
        inter.appid: 'wx452cb3d9a14e0d20'
        inter.machid: '1525669961'
        inter.callback.url: '${paycenter.chujian.host.url}/chujianpay/wx/callback'
        inter.tradeType: 'APP'
        inter.key: 'Z6L0IX8dsW7x1extgbHbCVZkIxpZVR9k'


chujian:
   token:
     key:
       public-key-string: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlTulF2dCQQiU4jkQMQHth084/OZcLFGkse6BQ0J5u47TOJ7PGPMAX1iqCrCwgbseDNLjMMpxLuX4ULbpjFrD/FN1uKmXEVwdP9zYCv22hE618XU6j3u0OEfsgZrupv9+lALxGZKyDfDRsjEy5KCXekAOiXDxJEUl/pNYla8MoJ5D9zjjUzUVq8i3pdL42sP9z6LKhtQXtzOiQ22zGST3mMzButpYXK55LHlgqYXb9hjBbcVIsZYP07Q4mt+NlT+x4crYp4Hirjl9rbUmQm7ZoL3GR8ErJnipPqOo7uKCAmwjKnBoRSu5836gG6kLOiSHtCdu8hp96G8sS95oWorflwIDAQAB'
   mta:
     log:
       enable: true
       path: ${FIRSTMEET_MSERVICE_DATA_BASEDIR:.}/logs/${HOSTNAME:1}/mta-log
   uid:
     enable: true


