spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.220:3306/user_center?useUnicode=true&characterEncoding=utf-8
    username: kaifa
    password: '{cipher}AQBzV0FjR1l0sSY2FLj88SFxBJISty93xfTamp2LZg09OlupL5wV5wwRqrAxPNdnvAA/7u4IJsiCyo7yLFLfwe8342XD2zvGWK1RS2O/UaclgAWGCwuT6P4BzekGKhKPmTMsFdSZ8RSiMKuvuMF3PVHT+lSaapj7lDhs5dfa/LYwMGMPaEwmkuNb79jS+iM4G5lQorhhZwPl+AgjPAf8Gg7YPwlrDTSuvuOcscECEsMj7qxXNtwIa1UiVtb6KmptMMtjsCxYVHtWVIpmwcVT39fCoEhNI4a2eMGJFEIJsHc5766ovOT3Lk2YPC1fF+d90FN/XrIUaUjkQA/GhCjlfVP57Hrz9CnPohxgfYV8ouz1ckQyxraVH8JSBaXRteCJyiI='
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  jpa:
    database: mysql
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
chujian:
  password:
    enable-encode: true
  token:
    key:
      jks-filepath: chujian.jks
      password: password
      alias: chujian
      public-key-string: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlTulF2dCQQiU4jkQMQHth084/OZcLFGkse6BQ0J5u47TOJ7PGPMAX1iqCrCwgbseDNLjMMpxLuX4ULbpjFrD/FN1uKmXEVwdP9zYCv22hE618XU6j3u0OEfsgZrupv9+lALxGZKyDfDRsjEy5KCXekAOiXDxJEUl/pNYla8MoJ5D9zjjUzUVq8i3pdL42sP9z6LKhtQXtzOiQ22zGST3mMzButpYXK55LHlgqYXb9hjBbcVIsZYP07Q4mt+NlT+x4crYp4Hirjl9rbUmQm7ZoL3GR8ErJnipPqOo7uKCAmwjKnBoRSu5836gG6kLOiSHtCdu8hp96G8sS95oWorflwIDAQAB
health:
  config:
    enabled: true
    time-to-live: 86400000
server:
  port: 8080
grpc:
  port: 6565
