server:
  ssl:
    key-store: classpath:https_keystore.p12
    key-store-password: chujian
    keyStoreType: PKCS12
    keyAlias: 1
  port: 8443
  http-port: 8080
  servlet:
    application-display-name: firstmeet-mservice-paycenter-yyb
    contextPath: /
  tomcat:
    basedir: "./"
    accesslog:
      enabled: true
      directory: ${FIRSTMEET_MSERVICE_DATA_BASEDIR:.}/logs/${HOSTNAME:1}/access-log
    customized.enable: true
    customized.accept-count: 100
    customized.max-threads: 200
    customized.min-spare-threads: 25
    customized.max-connections: 10000
    customized.connection-timeout: 2000
    manager.enable: false
    manager.context-path: '/data/webapps/manager'

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.220:3306/pay_center_yyb?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: kaifa
    password: '{cipher}AQDOU4Ujh3h0/jv4MvSOzyqiZi8ks40J+SbdQTSn/f5+3ewMmp1xC966H1iMfOE1RIOrQC+AJHIFtbiVooovKXj7DpgXFxh/eGD4wr4xhqf0XUkdsxJEYH465vmgMT97qAmahJj8TPHgdRLIczYu/k1z+jATkjUCOXUSlYKOwkZ7giUy06YbHgtPL79QOoJfzM0BAGivd+1HcdYQc1bdhZcqqBKLRj2Fb+Q7eADyoO4OMg2CWZeJ3NOLhhg6OHkrzca9v2fyyRmj8v0PsdK+nfPsc2RvmfZMk0wNLksfWBLN8NV3uT2Tyfbp1Qh571XndLrmZ1yBqqqEeW0k0qbogvMQm+DhL5Rfzq6iZmkoB+k9GlGH9kC1vwaIoDAEhqnqiEI='
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

yybpay:
  midas.url: 'https://ysdktest.qq.com'
  midas.exchangeRatio : 10

chujian:    
   drools:
      rule:
        path: 'classpath*:rules/**/client-config-dev.xls' #Can configure absolute path: file:/data/rules/**/*.drl

uid.grpc:
  host: 'uidgenerator.ups.firstmeet'
  port: 6565
