spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.220:3306/user_center_samsung?useUnicode=true&characterEncoding=utf-8
    username: kaifa
    password: '{cipher}AQCti8ljsPqAHvVPq+6KUQJTsqedRX/ZDApxXGKdid2bGgszXr+qYvxcCc7jx/c4J1VSgCazF9rXXJMGv0imC2eraPFX5p6iuQG74i1Yocm3quHx0yKZqOFEe4FPbThZSu8bQsSXr4wNvFwafK9T97LGBek+aGniirZ0Fpk+dMPn0umZHBxyXebABES51ZDbGZRHOwjecixGDW5xJDTjCFeqwiXcfdaFvrDb6955dLqb2Erqhm4YdqaS2EmzUi7csvx1avELGClSKZp8bAY/1yd94pFEvENuTSHS9VOh+j04SkbUqbbXOe16tZcd1Ux5xon5eUVntFAtAa1Xx+cPrBtxZI0uw8sunkWwOmjOyO+uLeN8EatIDQpqbELzeV/qVXk='
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
management:
  endpoints:
    web:
      exposure:
        include: '*'
samsung:
  login-verify:
    enabled: false
    method: external.hms.gs.checkPlayerSign
    url: https://gss-cn.game.hicloud.com/gameservice/api/gbClientApi
chujian:
  usercenter:
    hostname: usercenter.ups.firstmeet
    port: 6565
  uid-generator:
    hostname: uidgenerator.ups.firstmeet
    port: 6565
  drools:
    rule:
      path: 'classpath*:rules/**/*.drl'
server:
  tomcat:
    accesslog:
      enabled: true
      directory: ${FIRSTMEET_MSERVICE_DATA_BASEDIR:.}/logs/${HOSTNAME:1}/access-log
  port: 8080
grpc:
  port: 6565